[package]
name = "nasus"
version = "0.1.0"
edition = "2021"
description = "nasus is a blazing fast osu bancho IRC crate 🟢"
repository = ""
license = "MIT"

[dependencies]
futures = "0.3"
dotenv = "0.15.0" # TODO remove in next versions
peace-performance = "0.4.0"
reqwest = "0.11.14"
tokio = { version = "1.25.0", features = ["full"] }

[dev-dependencies]
dotenv = "0.15.0"
